# MÃO NA MASSA - TRAGA UM FILME DISTINCT EM REGISTROS REPETIDOS


# APENAS RETIRA AS DUPLICIDADES
SELECT DISTINCT F.TITULO, F.DESCRICAO, F.FILME_ID
FROM ALUGUEL A, FILME F, INVENTARIO I
WHERE A.INVENTARIO_ID = I.INVENTARIO_ID
AND F.FILME_ID = I.FILME_ID
ORDER BY TITULO;

# AGRUPAMENTO MAIS COMPLETO, AJUDA NAS FUNÇÕES DE AGRUPAMENTO COMO: SUM, AVG, COUNT, MAX, MIN E ECT..
SELECT F.TITULO, F.DESCRICAO, F.FILME_ID
FROM ALUGUEL A, FILME F, INVENTARIO I
WHERE A.INVENTARIO_ID = I.INVENTARIO_ID
AND F.FILME_ID = I.FILME_ID
GROUP BY F.TITULO, F.DESCRICAO
ORDER BY TITULO;