# FILTRANDO OCORRÊNCIAS DUPLICADAS PELA CLÁUSULA DISTINCT


SELECT DISTINCT F.TITULO, F.DESCRICAO, F.FILME_ID
FROM ALUGUEL A, FILME F, INVENTARIO I
WHERE A.INVENTARIO_ID = I.INVENTARIO_ID
AND F.FILME_ID = I.FILME_ID;
