
# RECUPERANDO A MÉDIA DOS VALORES DE UMA TABELA USANDO AVG()

SELECT AVG(A.PRECO_DA_LOCACAO)
FROM FILME A;


SELECT A.NOME CATEGORIA_DE_FILME, (AVG(B.PRECO_DA_LOCACAO)) MÉDIA_LOCAÇÃO, (AVG(B.CUSTO_DE_SUBSTITUICAO)) MÉDIA_CUSTO_SUBTITUIÇÃO 
FROM CATEGORIA A, FILME B, FILME_CATEGORIA C
WHERE A.CATEGORIA_ID = C.CATEGORIA_ID
AND B.FILME_ID = C.FILME_ID
AND A.CATEGORIA_ID = 1;