SELECT SUM(F.PRECO_DA_LOCACAO)
FROM FILME F;

SELECT * FROM FILME;

SELECT A.NOME CATEGORIA_DE_FILME, (SUM(B.PRECO_DA_LOCACAO)) TOTAL_LOCAÇÃO , (SUM(B.CUSTO_DE_SUBSTITUICAO)) TOTAL_CUSTO_SUBTITUIÇÃO 
FROM CATEGORIA A, FILME B, FILME_CATEGORIA C
WHERE A.CATEGORIA_ID = C.CATEGORIA_ID
AND B.FILME_ID = C.FILME_ID
AND A.CATEGORIA_ID = 1;