# DASHBOARDS - REPRESENTAÇÃO GRÁFICA DO QUE FOI RETORNADO NUMA QUERY
# ARQUIVO EM EXCEL COM O NOME DE ALUGUEIS_FILMES_TOTAIS MOSTRANDO DADOS RETIRADOS DA QUERY ABAIXO


SELECT A.NOME, SUM(B.PRECO_DA_LOCACAO)PRECO_DA_LOCACAO
FROM CATEGORIA A, FILME B, FILME_CATEGORIA C
WHERE A.CATEGORIA_ID = C.CATEGORIA_ID
AND B.FILME_ID = C.FILME_ID
GROUP BY A.NOME;

