#TUNING - ARTE DE DEIXAR A QUERY RÁPIDA

# DICAS
	# ANALISAR A TABELA, VERIRICAR INDICE;
	# UTILIZAR A CHAVE PRIMÁRIA, SE NÃO DER USE UM ATRIBUTO OU CARACTERÍSTICA NÚMERICA;
	# SEMPRE COLOCAR APELIDOS NA TABELA;
	# TENTAR SEMPRE NA CONDIÇÃO WHERE NÚMEROS E NÃO TEXTOS;
	
	
#EX:

SELECT A.NOME, B.TITULO, B.DESCRICAO, B.PRECO_DA_LOCACAO
FROM CATEGORIA A, FILME B, FILME_CATEGORIA C
WHERE A.CATEGORIA_ID = C.CATEGORIA_ID
AND B.FILME_ID = C.FILME_ID
ORDER BY 4;

# TEMPO DE EXECUÇÃO DA QUERY DE: 1000 row(s) returned


SELECT A.NOME, B.TITULO, B.DESCRICAO, B.PRECO_DA_LOCACAO
FROM CATEGORIA A, FILME B, FILME_CATEGORIA C
WHERE A.CATEGORIA_ID = C.CATEGORIA_ID
AND B.FILME_ID = C.FILME_ID
AND B.FILME_ID = 19
ORDER BY 4;	

# TEMPO DE EXECUÇÃO DA QUERY DE: 1 row(s) returned

