#JOINS DE TABELAS

SELECT * FROM ALUGUEL;

SELECT * FROM CLIENTE;

SELECT C.PRIMEIRO_NOME, C.ULTIMO_NOME, C.EMAIL, COUNT(*) QTD
FROM ALUGUEL A, CLIENTE C 
WHERE A.CLIENTE_ID = C.CLIENTE_ID
GROUP BY C.PRIMEIRO_NOME
ORDER BY C.PRIMEIRO_NOME;

