# SUBCONSULTAS

# TRAZ OS ENDEREÇOS DOS CLIENTES QUE ALUGARAM MENOS DE 20
# NÃO PODE TER ORDER BY
# O SUBSELECT TEM QUE TER APENAS UMA COLUNA, E ESTA COLUNA TEM QUE SER O MESMO QUE ESTA BUSCANDO NO SELECT PRINCIPAL OU MAIS EXTERNO.
 
SELECT * 
FROM ENDERECO E 
WHERE E.ENDERECO_ID 
IN
(SELECT C.ENDERECO_ID
FROM ALUGUEL A, CLIENTE C 
WHERE A.CLIENTE_ID = C.CLIENTE_ID
GROUP BY C.PRIMEIRO_NOME
HAVING COUNT(*) <= 20); 


#TRASER A DATA DO MAIOR ALUGUEL

SELECT MAX(A.DATA_DE_ALUGUEL) DATA_MAIOR_ALUGUEL
FROM ALUGUEL A 
WHERE A.ALUGUEL_ID 
IN
(SELECT A.ALUGUEL_ID
FROM ALUGUEL A, CLIENTE C 
WHERE A.CLIENTE_ID = C.CLIENTE_ID
GROUP BY C.PRIMEIRO_NOME
HAVING COUNT(*) <= 20); 


