# PROCURE O ÚLTIMO FILME ALUGADO DE SUA LOCADORA
# A LIGAÇÃO COM FILME ESTA EM INVENTÁRIO
# ULTIMA DATA_ALUGUEL DA TABELA ALUGUEL


SELECT * FROM ALUGUEL;

SELECT * FROM INVENTARIO;

SELECT * FROM FILME;


SELECT F.TITULO, A.DATA_DE_ALUGUEL, F.DESCRICAO
FROM ALUGUEL A, FILME F, INVENTARIO I
WHERE A.INVENTARIO_ID = I.INVENTARIO_ID
AND F.FILME_ID = I.FILME_ID
AND F.FILME_ID = 2
AND A.ALUGUEL_ID = 13421
ORDER BY DATA_DE_ALUGUEL DESC;